apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: vault-kubernetes-initializer
  name: vault-kubernetes-initializer
  namespace: secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-kubernetes-initializer
  template:
    metadata:
      labels:
        app: vault-kubernetes-initializer
      name: vault-kubernetes-initializer
    spec:
      containers:
        - name: vault-kubernetes-initializer
          image: vault-kubernetes-initializer:0.0.5
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: vault-kubernetes-initializer
initializers:
  - name: vault.initializer.kubernetes.io
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - deployments
