apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: secrets
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator-clusterrole
  namespace: secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: secrets
---
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-vault
  namespace: secrets
spec:
  template:
    spec:
      serviceAccountName: vault-auth
      restartPolicy: Never
      containers:
        - name: configure-vault
          image: vault:0.9.1
          env:
            - name: VAULT_ADDR
              value: http://vault:8200
            - name: VAULT_TOKEN
              value: root
          command:
            - sh
            - -c
            - |
                while ! nc -z vault 8200; do sleep 1; echo "Waiting for vault"; done

                vault auth-enable kubernetes && \
                vault write auth/kubernetes/config token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
                            kubernetes_host=https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT \
                            kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt &&

                vault write auth/kubernetes/role/demo-role \
                            bound_service_account_names=demo-sa \
                            bound_service_account_namespaces=demo \
                            policies=default \
                            ttl=1h
